### ISSUE TITLE
Usage of npm package redux-devtools-app

### ISSUE THREAD

**Issue by Methuselah96** [adamzasah/redux-devtools-app#8]
I was wondering if you would consider letting the redux-devtools team use the `redux-devtools-app` npm package name. We've made some changes including renaming a lot of the old `remotedev-*` packages to `redux-devtools-*`, but we had to make an exception for `remotedev-app` since this project is already using `redux-devtools-app`. All of our packages are currently located in the [redux-devtools monorepo](https://github.com/reduxjs/redux-devtools). We would of course give you credit for letting us use the name and start at a new major version number so that users could still use the old version if desired.

We also now have an electron app that can be launched from [our CLI](https://github.com/reduxjs/redux-devtools/tree/master/packages/redux-devtools-cli) that performs a similar functionality to this project.

Thanks for your consideration!

**Comment by adamzasah** [comment]
@Methuselah96 Hello. Haven't been active here for a while, so sorry for the late response. Thanks for letting me know. I will gladly leave name for you. It's nice to see, there is a CLI version now too, so I will migrate to that ASAP. Contact me and we can figure it out. 👍

**Comment by Methuselah96** [comment]
No problem, we actually moved all of our packages to a `@redux-devtools` namespace (e.g., `@redux-devtools/app`) so this is no longer necessary. Thanks for the reply!
